using BookManager.Orm.Model;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookManager.Model
{
    public class Borrowing : Entity<string>, IAutoGeneratedBusinessKey
    {
        public Guid BookId { get; set; }

        [NotMapped]
        public Book Book { get; set; }

        public DateTime Date { get; set; }

        public string FriendName { get; set; }

        public string AutoGeneratedBusinessKey { get; set; }

        public override string GetBusinessKey() => AutoGeneratedBusinessKey;
    }
}
