namespace BookManager.Orm.Model
{
    /// <summary>
    /// This interface must be implemented by those entities
    /// which don't have a unique, immutable field capable of being its BusinessKey
    /// </summary>
    public interface IAutoGeneratedBusinessKey
    {
        string AutoGeneratedBusinessKey { get; set; }
    }
}
